/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotesIndexRouteImport } from './routes/notes.index'
import { Route as NotesWasteRouteImport } from './routes/notes.waste'
import { Route as ToolsIndexRouteImport } from './routes/tools.index'
import { Route as ToolsBoardRouteImport } from './routes/tools.board'
import { Route as ToolsStockRouteImport } from './routes/tools.stock'
import { Route as ToolsWallRouteImport } from './routes/tools.wall'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIndexRoute = NotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesWasteRoute = NotesWasteRouteImport.update({
  id: '/notes/waste',
  path: '/notes/waste',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsIndexRoute = ToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsBoardRoute = ToolsBoardRouteImport.update({
  id: '/tools/board',
  path: '/tools/board',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsStockRoute = ToolsStockRouteImport.update({
  id: '/tools/stock',
  path: '/tools/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsWallRoute = ToolsWallRouteImport.update({
  id: '/tools/wall',
  path: '/tools/wall',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/notes/waste': typeof NotesWasteRoute
  '/tools/board': typeof ToolsBoardRoute
  '/tools/stock': typeof ToolsStockRoute
  '/tools/wall': typeof ToolsWallRoute
  '/notes/': typeof NotesIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/notes/waste': typeof NotesWasteRoute
  '/tools/board': typeof ToolsBoardRoute
  '/tools/stock': typeof ToolsStockRoute
  '/tools/wall': typeof ToolsWallRoute
  '/notes': typeof NotesIndexRoute
  '/tools': typeof ToolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/notes/waste': typeof NotesWasteRoute
  '/tools/board': typeof ToolsBoardRoute
  '/tools/stock': typeof ToolsStockRoute
  '/tools/wall': typeof ToolsWallRoute
  '/notes/': typeof NotesIndexRoute
  '/tools/': typeof ToolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/notes/waste'
    | '/tools/board'
    | '/tools/stock'
    | '/tools/wall'
    | '/notes/'
    | '/tools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/notes/waste'
    | '/tools/board'
    | '/tools/stock'
    | '/tools/wall'
    | '/notes'
    | '/tools'
  id:
    | '__root__'
    | '/'
    | '/notes/waste'
    | '/tools/board'
    | '/tools/stock'
    | '/tools/wall'
    | '/notes/'
    | '/tools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotesWasteRoute: typeof NotesWasteRoute
  ToolsBoardRoute: typeof ToolsBoardRoute
  ToolsStockRoute: typeof ToolsStockRoute
  ToolsWallRoute: typeof ToolsWallRoute
  NotesIndexRoute: typeof NotesIndexRoute
  ToolsIndexRoute: typeof ToolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/': {
      id: '/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof NotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/waste': {
      id: '/notes/waste'
      path: '/notes/waste'
      fullPath: '/notes/waste'
      preLoaderRoute: typeof NotesWasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/': {
      id: '/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof ToolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/board': {
      id: '/tools/board'
      path: '/tools/board'
      fullPath: '/tools/board'
      preLoaderRoute: typeof ToolsBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/stock': {
      id: '/tools/stock'
      path: '/tools/stock'
      fullPath: '/tools/stock'
      preLoaderRoute: typeof ToolsStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/wall': {
      id: '/tools/wall'
      path: '/tools/wall'
      fullPath: '/tools/wall'
      preLoaderRoute: typeof ToolsWallRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotesWasteRoute: NotesWasteRoute,
  ToolsBoardRoute: ToolsBoardRoute,
  ToolsStockRoute: ToolsStockRoute,
  ToolsWallRoute: ToolsWallRoute,
  NotesIndexRoute: NotesIndexRoute,
  ToolsIndexRoute: ToolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
